import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

import '../models/study_item.dart';

/// Loads the bundled study item dataset (assets/data/study_items.json),
/// generated by the backend/ pipeline from real VCAA study design files.
class StudyDataRepository {
  static const _assetPath = 'assets/data/study_items.json';

  /// Inputs: —. Outputs: `List<StudyItem>` — every item in the dataset.
  Future<List<StudyItem>> loadItems() async {
    final raw = await rootBundle.loadString(_assetPath);
    final decoded = jsonDecode(raw) as List<dynamic>;
    return decoded
        .map((json) => StudyItem.fromJson(json as Map<String, dynamic>))
        .toList();
  }
}
